---

# This is a sample configuration. To use it, copy it to local-configure.yml
# and edit.
#
# Medium configuration
# --------------------
#
# This is a good start for larger configurations.
# Just scale the client counts and cache/memory.
#
# This targets a medium server::
#
#     RAM: 2048MB
#     Cores: 2


# Things you MUST change
# ----------------------

admin_email: senaite@laboratoriosifa.tecnologia.bo

plone_initial_password: Bolivia444**

muninnode_query_ips:
    - ip.of.munin.monitor

# If you do not have a Munin monitor running, comment out the
# muninnode_query_ips and uncomment the line below:

# install_muninnode: no


# Major settings
# --------------

# Plone 4.3.x, 5.0.x, 5.1.x and 5.2.x are currently tested and working.
# Make sure this setting is quoted so that it's interpreted as a string.
plone_version: '5.2.15'

plone_python_version: '2.7.18'

# 2 clients
plone_client_count: 1

# smallish
plone_zodb_cache_size: 50000

# and enforce that with a memory-monitor
plone_client_max_memory: 1000MB

# with multiple clients, the "cron" hot monitor does a better job of avoiding downtime.
plone_hot_monitor: cron

install_proxycache: no

plone_create_site: no

plone_buildout_cfg: buildout.cfg

plone_instance_name: senaitelims
timezone: America/La_Paz

#plone_buildout_git_repo: https://github.com/hochkofler/ifalimsbuildout.git
#plone_buildout_git_version: main

#plone_target_path: /home/senaite
plone_additional_versions:
#    - senaite.lims = 2.6.0
    - et-xmlfile = 1.1.0
    - collective.recipe.backup = 4.2.0

plone_setuptools_version: '44.1.1'
plone_zc_buildout_version: '2.13.8'
mail_hostname: mail.laboratoriosifa.com

plone_extra_find_links:
    - https://dist.plone.org/release/5.2.15/
    - https://dist.plone.org/thirdparty/

#plone_additional_eggs:
#    - senaite.lims
